#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".

count=0
while [ $count -ne 11 ]
do
    if [ $count -eq 9 ]; then
	echo "Hi"
    else
	echo "Holberton School"
    fi
    ((count++))
done
